# Generated by Django 3.0.2 on 2020-03-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='responseText',
            new_name='response',
        ),
    ]
