# Generated by Django 3.0.2 on 2020-03-17 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0002_auto_20200317_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerResponse',
            fields=[
                ('custRespID', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(null=True)),
                ('custID', models.ForeignKey(db_column='custID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recommendationEngine.Customer')),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recommendationEngine.Questions')),
                ('responseID', models.ForeignKey(db_column='responseID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recommendationEngine.Responses')),
            ],
        ),
    ]
