# Generated by Django 3.0.4 on 2020-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0002_auto_20200327_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Qualitative', 'Qualitative'), ('Quantitative', 'Quantitative')], default='Quantitative', max_length=30),
        ),
    ]
