# Generated by Django 3.0.4 on 2020-03-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0003_question_question_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'question')},
        ),
    ]
