# Generated by Django 3.0.4 on 2020-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0004_auto_20200330_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image_path',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
