# Generated by Django 3.0.4 on 2020-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0005_auto_20200401_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vector',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
