# Generated by Django 3.0.4 on 2020-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0006_user_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vector',
            field=models.TextField(null=True),
        ),
    ]
