# Generated by Django 3.0.4 on 2020-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0007_auto_20200401_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=250, null=True)),
                ('data_dict', models.TextField(null=True)),
            ],
        ),
    ]
