# Generated by Django 3.0.4 on 2020-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0008_ocrimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
