# Generated by Django 3.0.4 on 2020-04-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0009_auto_20200424_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrimage',
            name='image_path',
            field=models.FileField(null=True, upload_to='floor_plans'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.FileField(null=True, upload_to='form_images'),
        ),
    ]
