# Generated by Django 3.0.4 on 2020-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0010_auto_20200427_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image_path',
            field=models.FileField(null=True, upload_to='answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_path',
            field=models.FileField(null=True, upload_to='questions'),
        ),
    ]
