# Generated by Django 3.0.4 on 2020-04-27 11:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0011_auto_20200427_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to='recommendationEngine.OCRImage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'image')},
        )
        
    ]
