# Generated by Django 3.0.4 on 2020-04-28 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0012_auto_20200427_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(null=True, upload_to='style_plans')),
                ('bedroom', models.PositiveIntegerField(default=1)),
                ('is_black', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendationEngine.StyleImage')),
            ],
        ),
    ]
