# Generated by Django 3.0.4 on 2020-04-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0013_styleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Qualitative', 'Qualitative'), ('Quantitative', 'Quantitative'), ('Style', 'Style')], default='Quantitative', max_length=30),
        ),
    ]
