# Generated by Django 3.0.4 on 2020-04-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0014_auto_20200428_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_style', to='recommendationEngine.StyleImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userstyle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
