# Generated by Django 3.0.4 on 2020-04-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0015_userstyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoredTextTestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FileField(null=True, upload_to='colored_text_test_plans')),
                ('data_dict', models.TextField(null=True)),
            ],
        ),
    ]
