# Generated by Django 3.0.4 on 2020-04-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0015_userstyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimage',
            name='bedroom',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
