# Generated by Django 3.0.4 on 2020-04-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0016_auto_20200429_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleimage',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
