# Generated by Django 3.0.4 on 2020-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0016_coloredtexttestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloredtexttestimage',
            name='image_path',
            field=models.ImageField(null=True, upload_to='colored_text_test_plans'),
        ),
    ]
