# Generated by Django 3.0.4 on 2020-04-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0017_auto_20200429_0720'),
        ('recommendationEngine', '0017_auto_20200429_1049'),
    ]

    operations = [
    ]
