# Generated by Django 3.0.4 on 2020-06-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0019_ganpredictimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_ocr', to=settings.AUTH_USER_MODEL),
        ),
    ]
