# Generated by Django 3.0.4 on 2020-08-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0021_auto_20200602_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='dim_dict',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together=set(),
        ),
    ]
