# Generated by Django 3.0.4 on 2020-08-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0022_auto_20200805_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrimage',
            name='dim_dict',
        ),
    ]
