# Generated by Django 3.0.4 on 2020-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0023_remove_ocrimage_dim_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrimage',
            name='dim_dict',
            field=models.TextField(null=True),
        ),
    ]
