# Generated by Django 3.0.4 on 2020-08-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0024_ocrimage_dim_dict'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('user', 'answer')},
        ),
    ]
