# Generated by Django 3.0.4 on 2020-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0026_auto_20200805_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='styleimage',
            name='length',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='styleimage',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
