# Generated by Django 3.0.4 on 2020-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0027_auto_20200811_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styleimage',
            name='parent',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
