# Generated by Django 3.0.4 on 2020-08-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendationEngine', '0028_auto_20200811_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='styleimage',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
